#!/usr/bin/env bash

# Checking Bash version
if (( ${BASH_VERSINFO[0]} < 4 )); then
    echo "This script needs at least bash version 4"
    exit 1
fi

this_basename="${0##*/}"

usage() {
    cat <<EOF
This is $this_basename

Usage: $this_basename [OPTIONS] <target snapshot> <sibling snapshots>

Description:
Defragmentation of an RO snapshot without modification or breaking parent relations

Options:
    -h, --help      Show this help
    -d, --debug     Debugging mode
    
EOF
}

cleanup() {
    if ! rmdir -v "${defragdir_tmp}"; then
        echo "Failed to remove ${defragdir_tmp}"
        exit 1
    fi
}

while [[ $1 == -* ]]; do
    case "$1" in
        -d|--debug)     opt_debug=1;                shift;;
        -h|--help)      usage;                      exit 0;;
        -*) echo "invalid option: $1" 1>&2; usage;  exit 1;;
    esac
done

target_snapshot="${1}";shift
sibling_snapshots=("${@}")

defragdir_tmp="$(mktemp -d "$(dirname "${target_snapshot}")/${this_basename}.XXXXXX")" || {
    echo "Failed to create temporary directory"
    exit 1
}

[[ -n "$opt_debug" ]] && echo "Target snapshot: ${target_snapshot}"
[[ -n "$opt_debug" ]] && echo "Sibling snapshots: ${sibling_snapshots[@]}"
[[ -n "$opt_debug" ]] && echo "Temporary defrag directory: ${defragdir_tmp}"

btrfs subvolume show "${target_snapshot}" | grep "Flags:.*readonly" > /dev/null || {
    echo "${target_snapshot} is not a RO snapshot"
    exit 1
}

new_sibling_snapshots=()

for sibling_snapshot in "${sibling_snapshots[@]}"; do
    # Remove target snapshot from siblings:
    if [[ "${sibling_snapshot}" != "${target_snapshot}" || -n "$found" ]]; then
        new_sibling_snapshots+=("${sibling_snapshot}")
    else
        found=1
    fi
    btrfs subvolume show "${sibling_snapshot}" | grep "Flags:.*readonly" > /dev/null || {
        echo "${sibling_snapshot} is not a RO snapshot"
        exit 1
    }
done
sibling_snapshots=("${new_sibling_snapshots}")

trap cleanup EXIT

if [[ ! -w "${defragdir_tmp}" ]]; then
    echo "${defragdir_tmp} is not writeable"
    exit 1
fi

if [[ -d "${target_snapshot}" ]]; then
    cd "${target_snapshot}"
else
    echo "Directory ${target_snapshot} does not exist"
    exit 1
fi

while read -r target_file; do
    [[ -n "$opt_debug" ]] && echo "##################### ${target_file}"
    if [[ -r "${target_file}" ]]; then
        cp -f --reflink=always "${target_file}" defragged || {
            echo "Copy ${target_file} failed"
            exit 1
        }
        btrfs fi defrag -t 512M defragged || {
            echo "Defragmentation of ${target_file} failed"
            exit 1
        }
        size="$(stat -c %s defragged)"
        
        for sibling_snapshot in "${sibling_snapshots[@]}"; do
            sibling_file="${sibling_snapshot}/${target_file}"
            if [[ -r "${sibling_file}" ]]; then
                btrfs-extent-same "$size" defragged 0 "${sibling_file}" || {
                    echo "btrfs-extent-same on ${sibling_file} failed"
                    exit 1
                }
            else
                [[ -n "$opt_debug" ]] && echo "No sibling file found for snapshot ${sibling_snapshot}"
            fi
        done
    else
        [[ -n "$opt_debug" ]] && echo "File is not readable: ${target_file}"
    fi
done < <(find . -type f)

