#!/usr/bin/env bash

this_basename="${0##*/}"


usage() {
    cat <<EOF
This is $this_basename

Usage: $this_basename [OPTIONS] <target snapshot> <sibling snapshots>

Description:
Defragmentation of an RO snapshot without modification or breaking parent relations

Options:
    -h, --help      Show this help
    -d, --debug     Debugging mode
    
EOF
}

while [[ $1 == -* ]]; do
    case "$1" in
        -d|--debug)     opt_debug=1;                shift;;
        -h|--help)      usage;                      exit 0;;
        -*) echo "invalid option: $1" 1>&2; usage;  exit 1;;
    esac
done

target_snapshot="${1}";shift
sibling_snapshots="${1}";shift

[[ -n opt_debug ]] && echo "target_snapshot: ${target_snapshot}"
[[ -n opt_debug ]] && echo "sibling_snapshots: ${sibling_snapshots}"


cd "${target_snapshot}"
while read -r targetfile; do
    [[ -n opt_debug ]] && echo "$targetfile"
    [[ -n opt_debug ]] && echo "${targetfile}"
done < <(find -type f)
